version: '3'
services:
  desafio-app:
    build:
      context: .
    ports:
      - "8282:8282"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"