name: Clean and Build

on:
  push:
    branches: [ "Michaella" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

      - name: Limpando o projeto
        run: mvn clean
      - name: Rodando sem testes
        run: mvn install -DskipTests

      - name: Run Maven integration tests
        run: mvn verify -DskipTests=false
