name: Java CI with Maven
on:
  push:
    branches: [ "LucasMenezes" ]
  pull_request:
    branches: [ "main" ]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Clean
        run: mvn clean

      - name: Install and skiping Tests
        run: mvn install -DskipTests



